### ISSUE TITLE
Mapping Description Column

### ISSUE THREAD

**Issue by slimbentami** [center-for-threat-informed-defense/attack-control-framework-mappings#53]
Hello,
First thank you for this work which is both needed and significant. I have two questions regarding the Mapping Description column in the speadsheets (r4 and r5):

- What does it mean when it is empty?
- The content otherwise seems to be the concatenation of the applicable SP 800-53 controls description. However in r5 i find "security assessment" which does not correspond to any control description. Is this a typo?

Thank you
Slim Bentami

**Comment by tiffb** [comment]
Slim, 

Thank you for your interest in this work.

If mapping description is empty, it just means that no notes were added by the individual doing the mapping. The Mapping Description column is not auto-generated, but rather filled in by various individuals and may vary based upon how they went about mappings or individual style.

The content is not necessarily exactly the control descriptions, but sometimes is more of a summary. The CA controls are for the Rev. 5 Assessment, Authorization, and Monitoring Control Family (renamed from Rev. 4 Security Assessment and Authorization Control Family) and will have descriptions related to that, such as "security assessment" (so it is likely not a typo).

Thanks,
Tiffany Bergeron
