### ISSUE TITLE
Equivalency with MITRE mitigations

### ISSUE THREAD

**Issue by slimbentami** [center-for-threat-informed-defense/attack-control-framework-mappings#54]
Hello,

Is the set of NIST controls mitigating a given technique/sub technique to be understood as equivalent to the set of MITRE mitigations mitigating the same technique/sub technique? 

I have so far assumed that the set of MITRE mitigations mitigating a given technique/sub technique when implemented will effectively mitigate it as best possible. So my question is really about figuring out if the same is true if one implements the set of NIST controls instead.

Have you considered mapping control to control instead which would help somewhat with this question?

Many thanks in advance,

Slim

**Comment by tiffb** [comment]
Slim, 

Thank you for submitting this issue. I’m not sure that I understand your questions, though. Please let us know if this answer doesn’t address your inquiry.

The mappings are between NIST controls and ATT&CK techniques, not mitigations. We use mitigations as our starting point when developing the mappings as they help us select techniques and then understand how a given control might apply, but we do not provide mappings of ATT&CK mitigations. 

Techniques may apply to more than one mitigation. Therefore, a particular subset of controls mapped to techniques addressed by a mitigation would need to be selected to identify those specific controls.

Thank you,

Tiffany Bergeron
