### ISSUE TITLE
subcontrol-of relationship between a control and an control enhancement appear to be missing in Rev 5

### ISSUE THREAD

**Issue by CyberDaedalus00** [center-for-threat-informed-defense/attack-control-framework-mappings#61]
In searching the frameworks/nist800-53-r5/stix/nist800-53-r5-mappings.json I don't see any relationships defined between the control and the control's enhancements.  For example, there is no subcontrol-of relationship between the course-of-action object representing the AC-2 "Account Management" control and its control enhancement AC-2(1) "Account Management | Automated System Account Management".

Is this a known limitation?

**Comment by isaisabel** [comment]
I can confirm that there are no subcontrol-of relationships in the output STIX. It looks like [the parser is implemented to build them](https://github.com/center-for-threat-informed-defense/attack-control-framework-mappings/blob/master/frameworks/nist800-53-r5/parse_controls.py#L133-L144), but they are not being built for somer reason. It's probably a bug, but will require some further digging to determine the exact cause.

**Comment by CyberDaedalus00** [comment]
It appears the issue is that when the nist800-53-r5-controls.tsv file was created, the column containing  related controls name changed from "related" to "related controls".  As a result, there was a place at line #54 in parse_controls.py that didn't get updated.  The fix was to change the value from "related" to "Related Controls" as shown below:

    `self.related = get_column("Related Controls").split(", ") if get_column("related") else []`
changes to 

    `self.related = get_column("Related Controls").split(", ") if get_column("Related Controls") else []`

This also fixed the issue where relationship between a control and related controls was also missing.
