### ISSUE TITLE
security baseline information is missing in NIST SP800-53 Rev 5 mappings

### ISSUE THREAD

**Issue by CyberDaedalus00** [center-for-threat-informed-defense/attack-control-framework-mappings#62]
I noticed that the Rev 5 mappings are missing the extended properties that indicate what baseline the particular control is used in.  There are available in the Rev 4 mappings.  Upon closer examination, I noticed that the nist800-53-r5-controls.tsv document doesn't contain the column that list the security baselines in which the controls are part. 

while I know that the security & privacy controls were moved from the NIST 800-53 Rev 5 document  to the new NIST 800-53B document, they are still part of the spec.  So, it seems they are not produced because the source document doesn't contain them (and the code to handle them has been removed).  

Is there any plan to incorporate them back into this mapping?

**Comment by tiffb** [comment]
Thank you for your request. It has not been a practice for us to include the NIST security control baselines (low/moderate/high) as part of this mappings project.
