### ISSUE TITLE
ATT&CK v12.1 mappings

### ISSUE THREAD

**Issue by MaurizioCasciano** [center-for-threat-informed-defense/attack-control-framework-mappings#90]
We need to update the MITRE ATT&CK mappings to v12.1

- https://github.com/mitre/cti/releases/tag/ATT%26CK-v12.1
- https://github.com/mitre/cti/tree/ATT%26CK-v12.1/enterprise-attack
- https://github.com/mitre/cti/blob/ATT%26CK-v12.1/enterprise-attack/enterprise-attack.json

**Comment by mehaase** [comment]
Thanks @MaurizioCasciano, we are in the process of updating this project to v12.1. I hope to share something here in a couple months.

**Comment by MaurizioCasciano** [comment]
Hi @mehaase, thanks. If there is something I can help with, just let me know how to proceed.

**Comment by mehaase** [comment]
HI @MaurizioCasciano, I'm following up on this thread to notify everybody that the 12.1 mappings are now released!
